
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const ContactDashboard = lazy(() => import("./pages/ContactDashboard.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/contact-dashboard", element: <UserGuard><ContactDashboard /></UserGuard>},
	{ path: "/contactdashboard", element: <UserGuard><ContactDashboard /></UserGuard>},

];
